import { Card } from "@/components/ui";
import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="max-w-3xl">
      <h1 className="font-display text-2xl font-bold tracking-tight mb-2">Terms of Service</h1>
      <p className="text-xs text-slate-500 mb-8">Last updated: March 2026</p>

      <div className="space-y-6 text-sm text-slate-400 leading-relaxed">
        <Card className="p-5">
          <h2 className="text-base font-bold text-slate-200 mb-3">1. Service Description</h2>
          <p>AI Cost Markets is a pricing intelligence platform that provides simulated prediction markets for AI model pricing. All trading on this platform uses simulated currency. No real money is at risk, deposited, or exchangeable.</p>
        </Card>

        <Card className="p-5">
          <h2 className="text-base font-bold text-slate-200 mb-3">2. Simulated Trading Disclosure</h2>
          <p>All market activity on AI Cost Markets is conducted with simulated funds. Market probabilities reflect aggregated user sentiment and are not financial advice, investment recommendations, or guarantees of future pricing outcomes. You should not rely solely on our market data for business decisions.</p>
        </Card>

        <Card className="p-5">
          <h2 className="text-base font-bold text-slate-200 mb-3">3. Accounts</h2>
          <p>You are responsible for maintaining the security of your account credentials. You must provide accurate information during registration. We reserve the right to suspend accounts that violate these terms.</p>
        </Card>

        <Card className="p-5">
          <h2 className="text-base font-bold text-slate-200 mb-3">4. Acceptable Use</h2>
          <p>You agree not to: attempt to manipulate markets through automated trading without authorization; reverse engineer the LMSR engine for commercial use; scrape data at rates exceeding our published API limits; impersonate other users; or use the service for any illegal purpose.</p>
        </Card>

        <Card className="p-5">
          <h2 className="text-base font-bold text-slate-200 mb-3">5. Intellectual Property</h2>
          <p>Market data, arbitrage insights, and builder projections generated by AI Cost Markets are proprietary. You may use outputs for your own business decisions but may not redistribute them commercially without written permission.</p>
        </Card>

        <Card className="p-5">
          <h2 className="text-base font-bold text-slate-200 mb-3">6. Disclaimer of Warranties</h2>
          <p>The service is provided &ldquo;as is&rdquo; without warranties of any kind. We do not guarantee the accuracy of market probabilities, builder projections, or arbitrage signals. Resolution of markets depends on third-party pricing decisions we do not control.</p>
        </Card>

        <Card className="p-5">
          <h2 className="text-base font-bold text-slate-200 mb-3">7. Limitation of Liability</h2>
          <p>AI Cost Markets shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service, including but not limited to business decisions made based on market data or builder recommendations.</p>
        </Card>

        <Card className="p-5">
          <h2 className="text-base font-bold text-slate-200 mb-3">8. Changes to Terms</h2>
          <p>We may update these terms at any time. Continued use of the service after changes constitutes acceptance. Material changes will be communicated via the platform.</p>
        </Card>

        <div className="text-xs text-slate-500 pt-4">
          Questions? Contact us at <span className="text-blue-400">legal@aicostmarkets.com</span> · <Link href="/privacy" className="text-blue-400 hover:underline">Privacy Policy</Link> · <Link href="/methodology" className="text-blue-400 hover:underline">How It Works</Link>
        </div>
      </div>
    </div>
  );
}
